### ISSUE TITLE
pravilnost algoritmov in izvajanje preizkusov

### ISSUE THREAD

**Issue by spela-1** [spela-1/Scheduling-Queues#2]
Zanima me, če bi lahko prosim preverili, če napisani algoritmi delujejo pravilno (file: algoritmi). Nekaj testov sva izvedla tudi sama, vendar ne najdeva rešenih primerov za vse algoritme.

Potem pa me zanima tudi, kako se lotiti izvajanja algoritmov na generiranih podatkih? Ali je smiselno, da se to izvaja na takšen način kot sva že začela (file: preizkusi)? Ali bi bilo smiselno, da uporabiva json?

lp

**Comment by jaanos** [comment]
Kolikor sem pogledal algoritme, izgleda, da bi morali delovati pravilno - so pa težko berljivi in najbrž po nepotrebnem zakomplicirani, tako da se nisem spuščal v podrobnosti. Tako le preverita na svojih testih, če izgledajo rešitve pravilno. Dobro bi bilo, da funkcije poleg povprečnega časa čakanja vračajo tudi sam vrstni red izvajanja opravil, npr. seznam teric oblike (čas, opravilo, trajanje izvajanja, preostali čas izvajanja), saj bo tako veliko lažje slediti izvajanju in ugotoviti morebitne napake.

Opažam sicer, da vrste implementirata tako, da dodajata na konec seznama in ga potem vsakič znova uredita - to je neučinkovito, saj vsako urejanje traja O(*n* log *n*) časa. Bolje bo, če v ta namen uporabita kopico - lahko uporabita v Python vgrajeni modul [`heapq`](https://docs.python.org/3/library/heapq.html). Ta vzdržuje kopico v seznamu - element na začetku seznama je tako element na začetku vrste (tj., najmanjši element), s funkcijama `heappush` in `heappop` pa dodajamo elemente v vrsto oziroma odstranimo prvi element iz vrste (obe operaciji trajata O(log *n*) časa). Koristilo bo tudi, če uvedeta razred za opravila:
```python
from dataclasses import dataclass, field

@dataclass(order=True)
class Opravilo:
    id: int=field(compare=False)
    arrival: float
    length: float
    predicted: float=field(default=None)

    def __post_init__(self): 
        if self.predicted is None: # če nimamo napovedi, naj bo enaka dolžini
            self.predicted = self.length
        assert self.arrival >= 0 and self.length > 0 and self.predicted > 0 # preverimo, da so podatki smiselni
```
Naj opomnim, da so tukaj podane le nespremenljive lastnosti opravil - preostali čas trajanja je npr. nekaj, kar med izvajanjem beležijo sami algoritmi.

Če imata seznam `seznam` trojic oz. četveric (ID opravila, čas prihoda, čas trajanja, ?predviden čas trajanja), lahko potem naredita seznam ustreznih objektov z
```python
opravila = sorted(Opravilo(*t) for t in seznam)
```

Vajine funkcije naj potem sprejemajo tak seznam (lahko predpostavita, da je že urejen). Potem lahko npr. pri `PSPJF` inicializirata vrsto kot prazen seznam in s funkcijami iz `heapq` dodajata elemente vanjo (kot trojice (kriterij, preostali čas, opravilo)) in odstranjujeta prvi element, npr.
```python
from heapq import heappop, heappush

def PSPJF(opravila):
    opravila = opravila + [Opravilo(None, float('inf'), float('inf'))] # zadnje, navidezno opravilo
    dogodki = []
    vrsta = []
    t = 0
    cakanje = 0
    for naslednje in opravila:
        while vrsta: # ponavljamo, dokler vrsta ni prazna
            prekinitev = naslednje.arrival - t # čas do prihoda naslednjega opravila
            if prekinitev <= 0:
                break # če je naslednje opravilo že prišlo, prekinemo zanko, da ga dodamo v vrsto
            predvideno, cas, opravilo = vrsta[0] # pogledamo opravilo na začetku vrste
            preostanek = cas - prekinitev # preostali čas trajanja po prihodu naslednjega opravila
            # naslednje opravilo bo prišlo pred koncem izvajanja trenutnega ima manjši predvideni čas trajanja
            if preostanek > 0 and predvideno > naslednje.predicted:
                dogodki.append((t, opravilo, prekinitev, preostanek)) # zabeležimo izvajanje do prekinitve
                vrsta[0] = (predvideno, preostanek, opravilo) # popravimo preostali čas
                t = naslednje.arrival # premaknemo se na čas prekinitve
                break # prekinemo zanko, da dodamo naslednje opravilo v vrsto
            else: # izvajanje se bo končalo
                dogodki.append((t, opravilo, cas, 0)) # zabeležimo dokončanje opravila
                heappop(vrsta) # odstranimo opravilo iz vrste
                t += cas # premaknemo se na čas konca izvajanja
                cakanje += t - opravilo.length - opravilo.arrival # zabeležimo čakanje
        else: # zanke nismo prekinili z break
            t = naslednje.arrival # premaknemo se naprej do časa prihoda naslednjega opravila
        heappush(vrsta, (naslednje.predicted, naslednje.length, naslednje)) # dodamo opravilo z začetno prioriteto enako dolžini 
    return cakanje, dogodki # bolj smiselno je, če vračata skupno čakanje, saj to ni odvisno le od števila opravil
```
Taka koda je veliko bolj berljiva, saj je takoj jasno, na kaj se nanašajo posamezna polja pri opravilih. Tudi druge algoritme, ki uporabljajo vrsto, lahko dobita z manjšimi spremembami v zgornjem - treba bo spremeniti le kriterij za razvrščanje in pogoj, kdaj se trenutno opravilo prekine. Seveda se pri `S(P)JF` to nikoli ne zgodi, tako da preostalega časa ni potrebno beležiti; pri `SRPT` pa je kriterij ravno enak preostalemu času, tako da ga lahko beležita samo enkrat.

Kar se izvajanja tiče, bi predlagal, da skupaj izvajata algoritme na "podobnih" podatkih (npr. ista predvidena trajanja, dejanska trajanja vsakič z drugačnim šumom) in iz tega poračunata povprečje (morda bi bilo smiselno pogledati tudi, kaj se dogaja z variabilnostjo - koliko posamezni rezultati odstopajo od povprečja) in to ponovita za različna števila opravil oziroma za različne jakosti šuma. Iz teh podatkov lahko potem narišeta ustrezne grafe, ki jih bosta prikazala v poročilu.
